- name: Installing nginx server
  hosts: local
  connection: local
  become: yes
  tasks: 
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: starting the service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes