- name: playbook for variables
  hosts: local
  connection: local
  vars_files:
    - course.yaml
    
  tasks:
    - name: Printing my course details
      ansible.builtin.debug:
      #vars refernce should be surrounded by ""
        msg: Hi guys, Strated learning {{ course }} from {{ trainer }} which is of {{duration}}
    