- name: practicing data types
  hosts: local
  become: yes
  connection: local
  vars:
    Duration: "120 hrs"
    trainer: "shiva kumar reddy"
    is_live: true
    course: Devops
    tools:  ##list
      - Linux
      - ansible
      - terraform
    concepts: ##dictonary-keyvalue pairs
      cicd: jenkins
      scripting: "shell, ansible, python"
  tasks:
    - name: printing my course and training info
      ansible.builtin.debug:
        msg: "Hi Guys!! I am learing course: {{ course }} from trainer: {{ trainer }} which is live {{ is_live }} amd its duration is {{ duration }} 
          tools are {{ tools }} and concepts are {{ concepts }}"


