- name: Conditions demo
  hosts: local
  connection: local
  become: yes

  vars_files:
    - course.yaml
  tasks:
    - name: checking the number is greater than 20
      ansible.builtin.debug:
        msg: "GIVEN NUMBER : {{ number }} is is greater than  20"
      when: number > 20

    - name: checking the given number is less than or equal to 50
      vars:
        number: 32
      ansible.builtin.debug:
        msg: "given number {{ number }} is less than or equal to 50"
      when: number <= 50
  
  