- name: Learning loops
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Printing my name and wife name
      ansible.builtin.debug:
        msg: " Hi guys!! my name is {{ item }}"
      loop:
        - Saiteja
        - anu
        - thippani