- name: USING loops
  hosts: frontend
  become: yes

  tasks:
  - name: installing packages using loops
    ansible.builtin.dnf:
      name: {{ item.name }}
      state: {{ item.state }}
    loop:
    - { name: nginx, state: removed }
    - { name: zip, state: installed }